FROM docker.io/library/golang@sha256:53eeac89074db483fdf0ab3be1df32bf6e47562263d2d0d6baa7f26acb4957dd

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential ca-certificates clang curl git llvm make pkg-config \
        protobuf-compiler bpftool libbpf-dev libelf-dev zlib1g-dev \
        tar unzip xz-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
